[server]
host = "0.0.0.0"
port = 7086
path = "/webdav"

fs_dir = "/tmp/flydav"
[auth]
    [[auth.user]]
    username = "pluveto"
    sub_fs_dir = "pluveto"
    sub_path = "pluveto"
    password_hash = "$2a$12$boxh0Exvu8TMwdsPx6uwsuRq4fq7UmulJ8OrXn41uOkO7U96.O.ly"
    password_crypt = "bcrypt"
    [[auth.user]]
    username = "admin"
    sub_fs_dir = ""
    sub_path = ""
    password_hash = "$2a$12$boxh0Exvu8TMwdsPx6uwsuRq4fq7UmulJ8OrXn41uOkO7U96.O.ly"
    password_crypt = "bcrypt"

[log]
level = "Warning"
    [[log.file]]
    format = "json"
    path = "/var/log/flydav.log"
    max_size = 1 # megabytes
    max_age = 28 # days

    [[log.stdout]]
    format = "text" # or "text"
    output = "stdout" # or "stderr"
