server:
  host: 0.0.0.0
  port: 7086
  path: /webdav
  fs_dir: /tmp/flydav
ui:
  enabled: false
  path: /ui
  source: /usr/share/flydav/ui
auth: {}
log:
  level: Warning
  file:
    - format: json
      path: /var/log/flydav.log
      max_size: 1
      max_age: 28
  stdout:
    - format: text
      output: stdout
cors:
  enabled: true
  allowed_origins:
    - '*'
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PROPFIND
    - PROPPATCH
    - MKCOL
    - COPY
    - MOVE
    - LOCK
    - UNLOCK
    - OPTIONS
    - HEAD
    - PATCH
  allowed_headers:
    - '*'
  exposed_headers:
    - '*'
  allow_credentials: true
  max_age: 86400
