[server]
host = "0.0.0.0"
port = 7086
path = "/webdav"
fs_dir = "/tmp/flydav"

[ui]
enabled = false
path = "/ui"
source = "/usr/share/flydav/ui"

[auth]

    # add more users here
    # note: the above line is required by auto install script, do not delete.

[log]
level = "Warning"
    [[log.file]]
    format = "json"
    path = "/var/log/flydav.log"
    max_size = 1 # megabytes
    max_age = 28 # days

    [[log.stdout]]
    format = "text" # or "text"
    output = "stdout" # or "stderr"
