name: Changelog
on:
  workflow_dispatch:
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Fetch depth 0 is required for Changelog generation
      - name: Checkout      
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print changelog
        run: |
          cat <<EOF
            ${{ steps.changelog.outputs.changes }}
          EOF